//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_WEATHEREntities : DbContext
    {
        public DB_WEATHEREntities()
            : base("name=DB_WEATHEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<DESCRIPTION> DESCRIPTIONs { get; set; }
        public virtual DbSet<PLACE> PLACEs { get; set; }
        public virtual DbSet<WEATHER> WEATHERs { get; set; }
    }
}
